UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 1;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 2;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 3;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 4;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 5;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 6;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 7;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 8;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 9;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 10;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 11;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 12;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 13;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 14;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 15;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 16;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 17;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 18;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 19;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 20;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 21;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 22;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 23;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 24;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 25;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 26;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 27;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 28;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 29;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 30;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 31;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 32;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 33;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 34;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 35;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 36;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 37;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 38;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 39;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 40;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 41;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 42;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 43;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 44;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 45;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 46;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 47;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 48;
UPDATE user_tb SET withdrawal_status = 'Y' WHERE user_id = 49;
UPDATE user_tb SET withdrawal_status = 'N' WHERE user_id = 50;

select *
from user_tb;


UPDATE user_tb SET user_address = '부산광역시 중구 중앙동 23-1', address_code = 9 WHERE user_id = 1;
UPDATE user_tb SET user_address = '전라북도 전주시 완산구 효자동 456-22', address_code = 12 WHERE user_id = 2;
UPDATE user_tb SET user_address = '충청북도 청주시 상당구 금천동 89-12', address_code = 4 WHERE user_id = 3;
UPDATE user_tb SET user_address = '광주광역시 서구 풍암동 789-34', address_code = 14 WHERE user_id = 4;
UPDATE user_tb SET user_address = '경상남도 창원시 성산구 중앙동 102-45', address_code = 6 WHERE user_id = 5;
UPDATE user_tb SET user_address = '대전광역시 중구 은행동 301-56', address_code = 2 WHERE user_id = 6;
UPDATE user_tb SET user_address = '서울특별시 종로구 삼청동 4-7', address_code = 0 WHERE user_id = 7;
UPDATE user_tb SET user_address = '충청남도 천안시 동남구 신부동 90-11', address_code = 5 WHERE user_id = 8;
UPDATE user_tb SET user_address = '강원도 강릉시 교동 502-67', address_code = 3 WHERE user_id = 9;
UPDATE user_tb SET user_address = '울산광역시 남구 삼산동 308-78', address_code = 10 WHERE user_id = 10;
UPDATE user_tb SET user_address = '전라남도 순천시 조곡동 678-90', address_code = 13 WHERE user_id = 11;
UPDATE user_tb SET user_address = '경상북도 포항시 남구 효자동 234-12', address_code = 7 WHERE user_id = 12;
UPDATE user_tb SET user_address = '경기도 수원시 팔달구 매산동 456-23', address_code = 1 WHERE user_id = 13;
UPDATE user_tb SET user_address = '경상남도 진주시 상대동 567-45', address_code = 8 WHERE user_id = 14;
UPDATE user_tb SET user_address = '제주특별자치도 제주시 일도2동 789-56', address_code = 15 WHERE user_id = 15;
UPDATE user_tb SET user_address = '충청남도 천안시 서북구 쌍용동 901-67', address_code = 5 WHERE user_id = 16;
UPDATE user_tb SET user_address = '전라남도 여수시 학동 234-89', address_code = 13 WHERE user_id = 17;
UPDATE user_tb SET user_address = '경상북도 경주시 용강동 345-90', address_code = 7 WHERE user_id = 18;
UPDATE user_tb SET user_address = '경기도 고양시 일산동구 장항동 678-12', address_code = 1 WHERE user_id = 19;
UPDATE user_tb SET user_address = '울산광역시 중구 옥교동 890-23', address_code = 10 WHERE user_id = 20;
UPDATE user_tb SET user_address = '경상남도 창원시 의창구 신월동 234-45', address_code = 6 WHERE user_id = 21;
UPDATE user_tb SET user_address = '전라북도 군산시 소룡동 456-67', address_code = 12 WHERE user_id = 22;
UPDATE user_tb SET user_address = '광주광역시 동구 충장로 678-89', address_code = 14 WHERE user_id = 23;
UPDATE user_tb SET user_address = '충청북도 제천시 장락동 901-23', address_code = 4 WHERE user_id = 24;
UPDATE user_tb SET user_address = '강원도 춘천시 효자동 345-12', address_code = 3 WHERE user_id = 25;
UPDATE user_tb SET user_address = '부산광역시 해운대구 우동 567-34', address_code = 9 WHERE user_id = 26;
UPDATE user_tb SET user_address = '대전광역시 동구 용운동 789-56', address_code = 2 WHERE user_id = 27;
UPDATE user_tb SET user_address = '대구광역시 달서구 신당동 901-67', address_code = 11 WHERE user_id = 28;
UPDATE user_tb SET user_address = '서울특별시 강남구 삼성동 234-89', address_code = 0 WHERE user_id = 29;
UPDATE user_tb SET user_address = '경상남도 김해시 장유동 456-90', address_code = 8 WHERE user_id = 30;
UPDATE user_tb SET user_address = '경상북도 안동시 옥동 678-12', address_code = 7 WHERE user_id = 31;
UPDATE user_tb SET user_address = '충청남도 아산시 온양동 890-23', address_code = 4 WHERE user_id = 32;
UPDATE user_tb SET user_address = '전라북도 익산시 남중동 234-45', address_code = 12 WHERE user_id = 33;
UPDATE user_tb SET user_address = '부산광역시 금정구 장전동 456-67', address_code = 9 WHERE user_id = 34;
UPDATE user_tb SET user_address = '충청남도 당진시 읍내동 678-89', address_code = 5 WHERE user_id = 35;
UPDATE user_tb SET user_address = '대구광역시 북구 침산동 901-23', address_code = 6 WHERE user_id = 36;
UPDATE user_tb SET user_address = '서울특별시 성동구 왕십리동 345-12', address_code = 0 WHERE user_id = 37;
UPDATE user_tb SET user_address = '울산광역시 울주군 온산읍 567-34', address_code = 10 WHERE user_id = 38;
UPDATE user_tb SET user_address = '경상남도 밀양시 삼문동 789-56', address_code = 3 WHERE user_id = 39;
UPDATE user_tb SET user_address = '광주광역시 남구 주월동 901-67', address_code = 14 WHERE user_id = 40;
UPDATE user_tb SET user_address = '경상북도 경산시 중산동 234-89', address_code = 8 WHERE user_id = 41;
UPDATE user_tb SET user_address = '경상남도 양산시 물금읍 456-90', address_code = 15 WHERE user_id = 42;
UPDATE user_tb SET user_address = '제주특별자치도 서귀포시 서귀동 678-12', address_code = 13 WHERE user_id = 43;
UPDATE user_tb SET user_address = '경기도 용인시 기흥구 구갈동 890-23', address_code = 2 WHERE user_id = 44;
UPDATE user_tb SET user_address = '대구광역시 수성구 범어동 234-45', address_code = 11 WHERE user_id = 45;
UPDATE user_tb SET user_address = '서울특별시 서대문구 창천동 456-67', address_code = 15 WHERE user_id = 46;
UPDATE user_tb SET user_address = '경상남도 사천시 사천읍 678-89', address_code = 2 WHERE user_id = 47;
UPDATE user_tb SET user_address = '서울특별시 종로구 인사동 901-23', address_code = 7 WHERE user_id = 48;
UPDATE user_tb SET user_address = '경상북도 구미시 형곡동 345-12', address_code = 5 WHERE user_id = 49;
UPDATE user_tb SET user_address = '서울시 강북구 쌍문동 124-77', address_code = 0 WHERE user_id = 50;
